accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('signup/', views.UserRegisterView.as_view(), name='signup'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name="profile"),
]

devbuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('room.urls')),
]

room/urls.py
from django.urls import path

from . import views


app_name = 'room'

urlpatterns = [
    path('', views.RoomIndexView.as_view(), name='index'),
    path('room/create', views.RoomCreateView.as_view(), name='create'),
    path('room/detail/<int:pk>/', views.room_detail_view, name='detail'),
    path('room/update/<int:pk>/', views.RoomUpdateView.as_view(), name='update'),
    path('room/delete/<int:pk>/', views.RoomDeleteView.as_view(), name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Email is required !')
        if not username:
            raise ValueError('Username is required !')

        email = self.normalize_email(email)
        user = self.model(
            username=username,
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        email = self.normalize_email(email)
        user = self.create_user(username=username, email=email, password=password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=250, unique=True)
    username = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm


User = get_user_model()


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput(
        attrs={
            'class': 'input'
        }
    ))

    confirm_password = forms.CharField(label='password再入力', widget=forms.PasswordInput(
        attrs={
            'class': 'input'
        }
    ))

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input'
        }
    ))

    email = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input'
        }
    ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise ValidationError('パスワードが一致しません')
    
    def save(self, commit=False):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'is_staff', 'is_active', 'is_superuser' )

    def clean_password(self):
        return self.initial['password']


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='メールアドレス', widget=forms.TextInput(
        attrs={
            'class': 'input',
            'placeholder': 'メールアドレス'
        }
    ))

    password = forms.CharField(label='パスワード', widget=forms.PasswordInput(
        attrs={
            'class': 'input',
            'placeholder': 'パスワード'
        }
    ))

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate
from django.views.generic import (
    FormView, View, CreateView, DetailView
)
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserLoginForm, UserCreationForm
from .models import User


class UserLoginView(FormView):
    template_name = 'accounts/accounts_login.html'
    form_class = UserLoginForm

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('room:index')
        else:
            form = UserLoginForm()
            return render(request, 'accounts/accounts_login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('room:index')
        return redirect('accounts:login')


class UserLogoutView(View):
    
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('accounts:login')


class UserRegisterView(CreateView):
    template_name = 'accounts/accounts_register.html'
    form_class = UserCreationForm

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('room:index')
        else:
            form = UserCreationForm()
            return render(request, 'accounts/accounts_register.html', {'form': form})
    
    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            login(request, user)
            return redirect('room:index')
        else:
            return redirect('accounts:signup')


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/accounts_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_rooms = context['user'].room_set.all()
        room_count = user_rooms.count()
        context['user_rooms'] = user_rooms
        context['room_count'] = room_count
        return context

templates/accounts/accounts_login.html
{% extends 'base.html' %}

{% block content %}

<div class="columns is-centered">
    <div class="column is-two-fifths">
        <h3 class="is-size-3 mt-4">ログイン</h3>
        <hr>
        <div class="has-background-link-light p-6">
            <form method="POST">
                {% csrf_token %}
                <div class="field">
                    <label class="label">メールアドレス</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="field">
                    <label class="label">パスワード</label>
                    {{ form.password }}
                    {{ form.password.errors}}
                </div>
                <div class="columns is-centered">
                    <button class="button is-primary is-centered mt-5" type="submit" value="ログイン">ログイン</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/accounts_profile.html
{% extends 'base.html' %}

{% block content %}

<div class="columns is-centered">
    <div class="column is-half">
        <h3 class="is-size-3 mt-4">{{ user.username }}</h3>
        <hr>
        <h3 class="is-size-4 mb-4"><span class="has-text-primary">{{ room_count }}</span> 件</h3>
        <div class="room-container">
            {% for user_room in user_rooms %}
                <div class="card mb-5 has-background-white-ter">
                    <header class="card-header">
                        <p class="card-header-title">
                            {{ user_room.name }}
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <div class="mb-3">
                                <a href="{% url 'accounts:profile' user_room.host.id %}">
                                    @{{ user_room.host }}
                                </a>
                            </div>
                            {{ user_room.description }}
                        </div>
                    </div>
                    <footer class="card-footer">
                        <a href="{% url 'room:detail' user_room.id %}" class="card-footer-item">詳細</a>
                        {% if request.user ==  user_room.host %}
                            <a href="{% url 'room:update' user_room.id %}" class="card-footer-item">編集</a>
                            <a href="{% url 'room:delete' user_room.id %}" class="card-footer-item">削除</a>
                        {% endif %}
                    </footer>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/accounts_register.html
{% extends 'base.html' %}

{% block content %}

<div class="columns is-centered">
    <div class="column is-two-fifths">
        <h3 class="is-size-3 mt-4">ユーザー登録</h3>
        <hr>
        <div class="has-background-link-light p-6">
            <form method="POST">
                {% csrf_token %}
                <div class="field">
                    <label class="label">ユーザーネーム</label>
                    {{ form.username }}
                </div>
                <div class="field">
                    <label class="label">メールアドレス</label>
                    {{ form.email }}
                </div>
                <div class="field">
                    <label class="label">パスワード</label>
                    {{ form.password }}
                </div>
                <div class="field">
                    <label class="label">確認パスワード</label>
                    {{ form.confirm_password }}
                </div>
                <div class="columns is-centered">
                    <button class="button is-primary is-centered mt-5" type="submit" value="ログイン">登録</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}