accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('signup/', views.UserRegisterView.as_view(), name='signup'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name="profile"),
]

devbuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('room.urls')),
]

room/urls.py
from django.urls import path

from . import views


app_name = 'room'

urlpatterns = [
    path('', views.RoomIndexView.as_view(), name='index'),
    path('room/create', views.RoomCreateView.as_view(), name='create'),
    path('room/detail/<int:pk>/', views.room_detail_view, name='detail'),
    path('room/update/<int:pk>/', views.RoomUpdateView.as_view(), name='update'),
    path('room/delete/<int:pk>/', views.RoomDeleteView.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <title>DevBuddy</title>
</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

templates/header.html
<header>
    <nav class="navbar is-link">
        <div class="navbar-brand">
            <a href="{% url 'room:index' %}" class="navbar-item is-size-3 ml-4">
                DevBuddy
            </a>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start">
                <div class="navbar-item">
                    <a href="{% url 'room:create' %}" class="has-text-white">ルーム作成</a>
                </div>
            </div>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if request.user.is_authenticated  %}
                            <p class="mr-5">
                                {{ request.user }} さんようこそ
                            </p>
                            <a href="{% url 'accounts:logout' %}" class="button is-primary mr-5">
                                ログアウト
                            </a>
                        {% else %}
                            <a href="{% url 'accounts:signup' %}" class="button is-primary mr-5">
                                <strong>新規登録</strong>
                            </a>
                            <a href="{% url 'accounts:login' %}" class="button is-light mr-5">
                                ログイン
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>